### ISSUE TITLE
How to make cluster config persistent?

### ISSUE THREAD

**Issue by felipeasf** [eBay/NuRaft#103]
Hello, how can I make the cluster config persistent? For example, if I have 3 servers instances online that are already part a cluster and all of them get offline at the same time. There is a way to make them reconnect to the same cluster? The first one to reconnect become master, and the others followers?
To achieve that, the only thing I need to do is implement the in_memory state_mgr.hxx file to save to the disk instead of use memory?

**Comment by greensky00** [comment]
Hi @felipeasf 
Yes, as we commented here
https://github.com/eBay/NuRaft/blob/89d7bd3469c2aeb3fe3658f5fd4a3c755ade8506/examples/in_memory_state_mgr.hxx#L51
you need to implement `save_config` and `load_config`, as well as `save_state` and `read_state`. Once those APIs are working, Raft server will automatically call them and reconstruct the last cluster info.

**Comment by felipeasf** [comment]
Thanks for the answer @greensky00 !
I didn't know about that part of the calls being automatic. I got it working =)
Another question is: There is a way to know when a slave becomes a master?

**Comment by greensky00** [comment]
You can register a callback function for hooking up a few events:
https://github.com/eBay/NuRaft/blob/972f02dd84aa2bcc4b9d7da5fdc1a63da21463ef/include/libnuraft/context.hxx#L58

The event for becoming a leader is defined here:
https://github.com/eBay/NuRaft/blob/972f02dd84aa2bcc4b9d7da5fdc1a63da21463ef/include/libnuraft/callback.hxx#L53

**Comment by felipeasf** [comment]
To register this callback I need the current context, right? As the context is created when the launcher.init function is called, how can I get the current context in order to set the callback?

**Comment by greensky00** [comment]
`context` is given at the initialization of Raft server and then becomes read-only. You need to set your callback function at the init time.

And now I realized that if someone uses `raft_launcher`, there is no way to set the callback function. A simple workaround for now is writing your own `init` function.

Seems to me the API that setting the callback function should be exposed outside. Will fix that soon. Thanks.

**Comment by felipeasf** [comment]
I wrote my own init function and is all good now!
Thanks for your kindly support!
