### ISSUE TITLE
Way to reject client request

### ISSUE THREAD

**Issue by FletcherJ1** [eBay/NuRaft#135]
Is there a way to reject a clients request? For example, they try to perform an operation that is invalid or wrong?

**Comment by greensky00** [comment]
@FletcherJ1 
The basic assumption is that all requests coming into NuRaft should be valid without any sabotage; Raft is not a Byzantine fault-tolerant protocol. NuRaft is doing basic CRC checking though.

If you want to filter them out, it should be done before the Raft; the module who calls NuRaft APIs (e.g., `raft_server::append_entries()`) is responsible for it.

**Comment by FletcherJ1** [comment]
Yeah I thought that it wouldn't be possible. Like you say, I'll just check beforehand.
Thanks!
