### ISSUE TITLE
move skip_initial_election_timeout_ option to raft_params

### ISSUE THREAD

**Issue by sheepgrass** [eBay/NuRaft#144]
Currently, skip_initial_election_timeout_ option is in init_options struct which can only configure through raft_server constructor.  It's not possible to configure it through raft_launcher.  Better move skip_initial_election_timeout_ option to raft_params.

Please review my PR #142 together with some other changes

**Comment by greensky00** [comment]
Merged PR https://github.com/eBay/NuRaft/pull/147.
