### ISSUE TITLE
How many nodes  at largest did eBay use in a production-scale  environment? 

### ISSUE THREAD

**Issue by triump2020** [eBay/NuRaft#167]
Hi  team ! 
     NuRaft's consistency Has  been rigorously verified?  BTW, how many nodes  at largest did eBay use in a production-scale  environment? 
  Thanks very much !

**Comment by triump2020** [comment]
In term of the design and Function, NuRaft is very excellent !

**Comment by greensky00** [comment]
Hi @triump2020 

We did a lot of internal tests including resiliency, endurance, and etc. NuRaft is being used in tens of thousands of servers in eBay.

**Comment by triump2020** [comment]
Great !
