### ISSUE TITLE
Question: Reads from followers

### ISSUE THREAD

**Issue by alesapin** [eBay/NuRaft#170]
What is the best-recommended way to execute read-only requests on the followers?

Seems likes it is unreliable to check `get_committed_log_idx() == get_leader_committed_log_idx()`? Is there any way to directly ask leader for it's `commited_log_idx`?

**Comment by greensky00** [comment]
Read-path is not a part of Raft protocol. You can use your own way to ask the leader for its committed index.

`get_leader_committed_log_idx()` returns the last "seen" committed index from heartbeats or `append_entries` messages from the leader. So it can be outdated at the time when a follower reads this value.

But please note that even though a follower directly asks the leader for the committed index, that value also can be outdated at the time when the follower receives the response from the leader. So there is no guarantee in either way.

**Comment by alesapin** [comment]
Thanks, I think stale reads are OK in my case. What is the best way to check that we are not completely partitioned from the leader (still receiving heartbeats)? https://github.com/eBay/NuRaft/blob/master/include/libnuraft/raft_server.hxx#L442-L444?

**Comment by greensky00** [comment]
I see. For that purpose, you can use this API
https://github.com/eBay/NuRaft/blob/c621949cab25f0f3b02c73487d07ac43cc06ce56/include/libnuraft/raft_server.hxx#L437-L445

It returns `false` if a follower is partitioned from the leader.

**Comment by alesapin** [comment]
Thanks!
