### ISSUE TITLE
Callback about commit result on follower

### ISSUE THREAD

**Issue by alesapin** [eBay/NuRaft#175]
Is there any way to subscribe to `commit` events in the state_machine? As far as I see there is no callback for it: https://github.com/eBay/NuRaft/blob/master/include/libnuraft/callback.hxx. `StateMachineExecution` seems suitable, but I need to get the result of the commit (from the state_machine) in my callback.

Also, I'm not sure, is it safe to make such a callback directly from state_machine's `commit` method? According to https://github.com/ClickHouse-Extras/NuRaft/blob/master/src/handle_commit.cxx#L270-L272 seems like yes, but it would be much better if you'll confirm this.

**Comment by greensky00** [comment]
@alesapin 
Yes, you can put whatever you want into `state_machine::commit()`. But please note that `commit()` will not be invoked for Raft's internal configuration change (such as adding/removing server).

**Comment by greensky00** [comment]
By the way, we are a heavy user of ClickHouse in eBay. Are you interested in the collaboration with us regarding this ZooKeeper issue? Then I will let our chief architect reach out to you.

**Comment by alesapin** [comment]
> By the way, we are a heavy user of ClickHouse in eBay. Are you interested in the collaboration with us regarding this ZooKeeper issue? Then I will let our chief architect reach out to you.

Thanks :) I'll discuss with сolleagues.

**Comment by alesapin** [comment]
We are interested to discuss any kind of collaboration.

**Comment by greensky00** [comment]
Sounds great, I will let him know.
