### ISSUE TITLE
Strange situation after leader outage

### ISSUE THREAD

**Issue by alesapin** [eBay/NuRaft#176]
I have a cluster (`auto_forwarding_` enabled) with 3 nodes: `node1` (priority 3), `node2` (priority 2), `node3` (priority 1). When I simulate network outage for `node1`, `node2` and `node3` select new leader quite fast and everything continues to work well. But very rarely something strange happens and they cannot make any progress for about 5-10 minutes.

Logs from `node2` https://gist.github.com/alesapin/502b6abea98d54cf83eed3b87e7e1aa7 and from `node3` https://gist.github.com/alesapin/f0abe77e6f323f9068138d5b26084af8. Seems like `node3` asks `node2` to append the same log entry (idx 152) again and again, but `node2` successfully processes this entry and responds to `node3`. `node3` receives the response but make the same request again?

Just trying to understand what is going on. Why it resolves without any help after 10 minutes? It happens very rarely, maybe it's related to `auto_forwarding_`? I'll try to reproduce without it.

**Comment by greensky00** [comment]
Hi @alesapin 
Seems like the leader election was successfully done quickly (node 3 became the leader within 1 second).

Node 3:
```
2021.02.04 22:45:54.578642 [ 63 ] {} <Warning> RaftInstance: Server is elected as leader for term 2
```

Node 2:
```
2021.02.04 22:45:54.577455 [ 22 ] {} <Information> RaftInstance:   FOLLOWER
```

The message that Node 3 was continuously sending was heartbeat; in Raft, there is no separation between heartbeat and append_entries request (please refer to [paper](https://raft.github.io/raft.pdf), Figure 2 at page 4). It sent the log 152 (the last log it had at that time) at first, and then Node 2 accepted and stored it. After that, Node 3 sent an empty message as a heartbeat, with the last log index and committed log index, which was 152 too.

You can see the Node 3's log that it sent log 152,
```
2021.02.04 22:45:54.579249 [ 63 ] {} <Notice> RaftInstance: append_entries for 2 with LastLogIndex=151, LastLogTerm=1, EntriesLength=1, CommitIndex=151, Term=2, peer_last_sent_idx 0
```
and after that, it sent an empty message (`EntriesLength=0`), with the last log/commit index info.
```
2021.02.04 22:45:54.581362 [ 31 ] {} <Notice> RaftInstance: append_entries for 2 with LastLogIndex=152, LastLogTerm=2, EntriesLength=0, CommitIndex=152, Term=2, peer_last_sent_idx 152
```

10 minutes later, Node received a new client request, and appended log 153.
```
2021.02.04 22:55:59.558464 [ 22 ] {} <Notice> RaftInstance: Receive a client_request message from 0 with LastLogIndex=0, LastLogTerm=0, EntriesLength=1, CommitIndex=0 and Term=0
2021.02.04 22:55:59.558599 [ 22 ] {} <Notice> RaftInstance: append at log_idx 153
```

So everything looks normal.

**Comment by alesapin** [comment]
Thanks!
