### ISSUE TITLE
Joint Consensus

### ISSUE THREAD

**Issue by triump2020** [eBay/NuRaft#177]
Hi  ,  Dose NuRaft support configure change by using joint consensus ?   or  hava a plan to support it in the future?

**Comment by greensky00** [comment]
Hi @triump2020 

It does not have the joint consensus logic as described in the paper. Instead, NuRaft allows only one server to be added or removed (there is no "replace") in a single configuration change. We avoid disjoint majorities by doing this in conjunction with the pre-vote protocol.

**Comment by triump2020** [comment]
@greensky00   Thanks for your response !
