### ISSUE TITLE
Potential segfault on server statup

### ISSUE THREAD

**Issue by alesapin** [eBay/NuRaft#194]
Hi! Recently, I've got the following error https://gist.github.com/alesapin/0dbbc2616a6b88d6a14467fd78dc922a on server startup. Actually, this specific error is not important, but the idea to start some threads from a partially initialized object doesn't look good:
https://github.com/eBay/NuRaft/blob/master/src/raft_server.cxx#L252-L257

So in my case background threads were fast enough to do something and call my callback which (in my case) checks that the current node is Leader. And all these things have happened before the constructor of `raft_server` was finished. So such behavior makes `raft_server` object very dangerous not only for user callbacks but also for its own code which executes in background threads. Maybe we can introduce some kind of `startup()` method which will start all background threads after the object already initialized?

**Comment by alesapin** [comment]
Also, I have a question. Is there any way from a user code to detect that the current server is ready to serve requests? By this, I mean that the server applied all uncommitted entries to its state machine and see the leader node or this node is the leader itself.
Seems like neither `BecomeLeader` nor `BecomeFresh` are not reliable ways to detect it.

**Comment by greensky00** [comment]
@alesapin 
There is `is_initialized()` API to check if the Raft is ready (either it becomes leader or receives the first heartbeat from the existing leader). But that won't be the case for you if your background thread is doing something with `raft_server` before the constructor is done. We also internally use an atomic flag, `running` for example:
```c++
raftServer = cs_new<raft_server>(ctx, i_opt);
...
running = true;
```
but that is not the part of Raft. I think your PR https://github.com/eBay/NuRaft/pull/195 seems reasonable to avoid the issue without maintaining external flags.

**Comment by alesapin** [comment]
Thanks, let's close this one.
