### ISSUE TITLE
Race condition between `create_snapshot` and `read_logical_snp_obj`

### ISSUE THREAD

**Issue by alesapin** [eBay/NuRaft#212]
Hi! 

In my state machine implementation, I'm always using the single latest snapshot. I've encountered the following case:
```
2021.05.05 21:35:46.899607 [ 1861 ] {} <Information> RaftInstance: creating a snapshot for index 1100
2021.05.05 21:35:46.899616 [ 1861 ] {} <Information> RaftInstance: create snapshot idx 1100 log_term 1
2021.05.05 21:35:46.899634 [ 1861 ] {} <Debug> KeeperStateMachine: Creating snapshot 1100
2021.05.05 21:35:46.899668 [ 1861 ] {} <Debug> KeeperStateMachine: In memory snapshot 1100 created, queueing task to flash to disk
2021.05.05 21:35:46.900040 [ 1861 ] {} <Information> RaftInstance: create snapshot idx 1100 log_term 1 done: 411 us elapsed
2021.05.05 21:35:46.922391 [ 1862 ] {} <Debug> RaftInstance: send snapshot peer 3, peer log idx: 465, my starting idx: 991, my log idx: 1104, last_snapshot_log_idx: 1000
2021.05.05 21:35:46.922406 [ 1862 ] {} <Debug> RaftInstance: previous sync_ctx exists 0x7f9eccdcf418, offset 1, snp idx 1000, user_ctx (nil)
2021.05.05 21:35:46.922417 [ 1862 ] {} <Debug> RaftInstance: peer: 3, obj_idx: 1, user_snp_ctx (nil)
2021.05.05 21:35:46.922428 [ 1862 ] {} <Debug> KeeperStateMachine: Reading snapshot 1000 obj_id 1
2021.05.05 21:35:46.947817 [ 1855 ] {} <Debug> KeeperStateMachine: Created persistent snapshot 1100 with path /home/robot-clickhouse/db/coordination/snapshots/snapshot_1100.bin
DB::Exception Required to read snapshot with last log index 1000, but our last log index is 1100, Stack trace (when copying this message, always include the lines below):
```

Thus, the leader server already finished creating 1100-idx snapshot, but was requested to read 1000-idx snapshot. What can we do in this case? Seems like the return code of `read_logical_snp_obj` is ignored in the library code.

**Comment by greensky00** [comment]
@alesapin 
Thanks for catching this. I will add a fix to that, and you can return `0` in `read_logical_snp_obj`, then Raft will retry with the latest snapshot in the next turn.

If your state machine operation is idempotent so that multiple executions can bring the same result, you can always return the latest snapshot whatever Raft requests.

**Comment by greensky00** [comment]
https://github.com/eBay/NuRaft/pull/213
Realized that returning `0` is used for successful cases in example and test codes (the description was incorrect). You should return a negative number to inform the read failure.

**Comment by alesapin** [comment]
Thanks.
