### ISSUE TITLE
Node identity

### ISSUE THREAD

**Issue by kishorekrd** [eBay/NuRaft#229]
Hi, In the example programs, the nodes are identified with node id and endpoint. What if any node goes down and comes back with different node id or endpoint? Is there any way to identify the node unique way other than node id and endpoint? 

For example, if there are 3 nodes in the cluster, (node 0(IP0), node 1(IP1), node 2(IP2)) and node 2 goes down. Now node 2 comes back as node 3(IP3). Is there any way raft automatically detects this node as previous node 2(IP2) and updates the cluster membership as (node 0(IP0), node 1(IP1), node 3(IP3)) ? Off course, I can manually remove node 2(IP2) and add node 3(IP3).

**Comment by greensky00** [comment]
Hi @kishorekrd 

No, it will not accept detect the IP address change automatically, and you need to manually remove and re-add it with the new IP address.

The reason why is because the change of cluster config (the list of members in the group) is treated as a single "append entry" operation -- it should append a log and reach the consensus, and consequently all (at least more than a majority) members should have the same config, not just the leader.

**Comment by kishorekrd** [comment]
Thanks, that make sense. Leader needs to know the new node3(IP3) details, so that we can remove node2(IP2) and then add node3(IP3). Couple of more questions.

Assume that leader is at last_log_index X. 
node2 goes down and comes back as node3. 
Now leader is at last_log_index Y. 
We removed node2 and added node3. 
In this case does leader 
     treats the node3 as a new node and send all the old log records or 
     treats it as a node that came back and send only log records from X+1 to Y? 

If it treats as a new node, is there any way to recognize it as a node that came back and only send log records from X+1 to Y?

Another question is, is there any way to identify a node uniquely irrespective of its node id or IP address change?

**Comment by greensky00** [comment]
Regarding the first question -- the leader will send logs from `X+1` to `Y`, as long as those logs exist in the leader's log store.

The second question -- server ID itself is the unique identifier throughout the entire library.

**Comment by zeromem** [comment]
Hi sorry to touch this closed issue again. I meet the same issue, in our k8s env, the ip port will be changed after restarting and the server_id will be the same as before. And we encounter the error that other instances can't connect to the new one. 

My question is, if the server_id is the unique identifier, is this possible that just store server_id, and load servers' ip port(and other settings) dynamically (reload from config and refresh the connections)

**Comment by greensky00** [comment]
Hi @zeromem 
After this thread closed, we recently introduced [custom resolver](https://github.com/eBay/NuRaft/blob/master/docs/custom_resolver.md). Maybe this will help your case?
