### ISSUE TITLE
A lot of "cancelled non-blocking client request" with async API 

### ISSUE THREAD

**Issue by alesapin** [eBay/NuRaft#239]
It seems like during server start when we apply non-snapshotted log records to the state machine we add elements to the `commit_ret_elems_` https://github.com/eBay/NuRaft/blame/master/src/handle_commit.cxx#L353 even for async_handler API. But nobody will erase them, and during the shutdown, we will get a lot of `cancelled non-blocking client request` in `drop_all_pending_commit_elems`.

BTW I don't understand why we care about `commit_ret_elems_` for non-blocking mode: https://github.com/ebay/NuRaft/blob/master/include/libnuraft/raft_server.hxx#L1270

**Comment by greensky00** [comment]
The comment in this line is outdated. `commit_ret_elems_` is used for async mode too, as the result of the state machine execution should be delivered to the user through this structure.
https://github.com/eBay/NuRaft/blob/29c28d1d70aa7d0e5205585373366b22adbf5ab0/include/libnuraft/raft_server.hxx#L1270

If you think this log is verbose, we can adjust the log level.
