### ISSUE TITLE
commited by all nodes is not supported

### ISSUE THREAD

**Issue by guoxiangzhou** [eBay/NuRaft#252]
I modify the code in raft_server.cxx ：
int32 raft_server::get_quorum_for_commit() {
    ptr<raft_params> params = ctx_->get_params();
    int32 num_voting_members = get_num_voting_members();
    return num_voting_members;
}

Then start the three nodes in turn：
./calc_server 1 localhost:10001
./calc_server 2 localhost:10002
./calc_server 3 localhost:10003

then add node 2/3 on node 1:
calc 1> add 2 localhost:10002
calc 1> add 3 localhost:10003, (crash)

In theory, should raft support full commit？

**Comment by guoxiangzhou** [comment]
int32 raft_server::get_quorum_for_commit() {
ptr<raft_params> params = ctx_->get_params();
int32 num_voting_members = get_num_voting_members();
return num_voting_members - 1;
}

use this code, It seems to be working well

**Comment by greensky00** [comment]
@guoxiangzhou 
FYI, there are already options to adjust the quorum size, without changing the code:
https://github.com/eBay/NuRaft/blob/master/docs/custom_quorum_size.md

**Comment by guoxiangzhou** [comment]
thx, I see
