### ISSUE TITLE
some questions about threading model

### ISSUE THREAD

**Issue by guoxiangzhou** [eBay/NuRaft#257]
https://github.com/eBay/NuRaft/blob/master/docs/replication_flow.md

State machine's functions(group1) execute in Background commit thread,
- commit 
- create_snapshot

State machine's functions(group2) execute in User threads and threads from Asio thread pool
- precommit
- rollback
- read_logical_snp_obj
- save_logical_snp_obj
- apply_snapshot

Although group1 and group2 are executed by different threads, they should not be executed at the same time, right?
So, in the calc example,
std::atomic<int64_ t> cur_ value_;
std::atomic<uint64_ t> last_ committed_ idx_;

Can it be written directly as:

int64_ t cur_ value_;
uint64_ t last_ committed_ idx_;

**Comment by guoxiangzhou** [comment]
As a user, when writing the state machine, I have been struggling with whether to use mutex and how to control the granularity. Can only one thread enter the member function of state machine at a time? According to the above understanding, can mutex not be used?

**Comment by guoxiangzhou** [comment]
I mean only for the user's context, like cur_value_, not include snapshots_. create_snapshot, read_logical_snp_obj may be executed at the same time， but these two functions do not modify the user context. create_snapshot read user context， commit/save_logical_snp_obj/rollback maybe modify the user context，but these functions do not execute at the same time. I don't know if my understanding is correct。

**Comment by greensky00** [comment]
Hi @guoxiangzhou 

The basic assumption is that the state machine APIs should be thread-safe against concurrent calls.

In more detail, please note that
* `pre_commit` and `rollback` are not part of the original Raft -- it is just for customizing the protocol. Current examples do not use these APIs. If you use them, that is at your own risk.
* There will be no concurrent calls for each `commit`, `pre_commit`, `rollback`, and `create_snapshot` APIs. That means, there will be only one `commit`, `pre_commit`, `rollback`, and `create_snapshot` call at a time.
* While `commit` is being executed, `pre_commit` or `read_logical_snp_obj` can be called from different threads concurrently.
* While `save_logical_snp_obj` and `apply_snapshot` are being executed, there will be no `commit`, `pre_commit`, `rollback`, `create_snapshot`, and `read_logical_snp_obj`.

If you want to allow only one thread to modify the state machine, I recommend you define `mutex` in your state machine and use it for all mutation APIs.

**Comment by guoxiangzhou** [comment]
thx
