### ISSUE TITLE
The StateManager::save_state function is called twice at startup

### ISSUE THREAD

**Issue by guoxiangzhou** [eBay/NuRaft#260]
When my program started, I found that the StateManager::save_state function was called twice,

in handle_vote.cxx

164: raft_server::initiate_vote(bool force_vote)
            ...
`208: ctx_->state_mgr_->save_state(*state_);`
209: request_vote(force_vote);

218: void raft_server::request_vote(bool force_vote) {
219:    state_->set_voted_for(id_);
`220:    ctx_->state_mgr_->save_state(*state_);`

Is it repeated?

**Comment by greensky00** [comment]
Hi @guoxiangzhou 
Thanks for catching this. You're right, `save_state` is unnecessarily called twice for the same round of the vote. We can remove the `save_state` in `initiate_vote` as it will call `request_vote` right after that.

**Comment by greensky00** [comment]
https://github.com/eBay/NuRaft/pull/262
