### ISSUE TITLE
Support non-blocking snapshot

### ISSUE THREAD

**Issue by JackyWoo** [eBay/NuRaft#275]
### Use case

Now creating snpashot is blocking. In case like Zookeeper, a snapshot will be 10GB and creating snapshot will cost about 1 minute with  HDD disk which will lead large user request blocking.
 
So, will NuRaft support non-blocking snapshot?

**Comment by JackyWoo** [comment]
What confused me is that if NuRaft support non-blocking snapsht,  maybe there are some variables issues.

`state_machine::create_snapshot` method has reference parameter type but inovked with local object.

https://github.com/eBay/NuRaft/blob/1b08f254fb646eeb7f21175ff866661d986d593c/include/libnuraft/state_machine.hxx#L292
https://github.com/eBay/NuRaft/blob/1b08f254fb646eeb7f21175ff866661d986d593c/src/handle_commit.cxx#L515-L527

**Comment by JackyWoo** [comment]
Hi @greensky00 thanks  you. I wandor whether we should add an asynchronous snapshot example?

**Comment by greensky00** [comment]
Added a new example for async snapshot creation. Please refer to
https://github.com/eBay/NuRaft/blob/7bfe977554185a77d31aa68e3e9f99d97a99d458/examples/calculator/calc_state_machine.hxx#L204-L214
