### ISSUE TITLE
Support build with bazel

### ISSUE THREAD

**Issue by lizhanhui** [eBay/NuRaft#284]
Hi,

We are building an application on top of NuRaft to achieve service continuity in case of node loss and we are using [Bazel](https://bazel.build/) to build and manage dependencies. 

Creating this issue is to ask if you guys would accept a pull-request supporting build NuRaft using Bazel, which may be helpful to other developers of Bazel community.

**Comment by greensky00** [comment]
Hi @lizhanhui 

Your PR is welcome as long as it doesn't break the existing CMake-based build. Thanks!
