### ISSUE TITLE
Question of why set `last_config` to `last uncommitted config` in log when node becomes leader

### ISSUE THREAD

**Issue by JackyWoo** [eBay/NuRaft#292]
Hi @greensky00, I have a question of why set `last_config` to `last uncommitted config` in log when node becomes leader.

If broadcast the `last uncommitted config` in log, whether  the newest `last_config` will be ignored?

```
// If there are uncommitted logs, search if conf log exists.
        ptr<cluster_config> last_config = get_config();

        ulong s_idx = sm_commit_index_ + 1;
        ulong e_idx = log_store_->next_slot();
        for (ulong ii = s_idx; ii < e_idx; ++ii) {
            ptr<log_entry> le = log_store_->entry_at(ii);
            if (le->get_val_type() != log_val_type::conf) continue;

            p_in("found uncommitted config at %zu, size %zu",
                 ii, le->get_buf().size());
            last_config = cluster_config::deserialize(le->get_buf());
        }
```

**Comment by greensky00** [comment]
It is the same as committing normal logs. When a member becomes a leader, it attempts to replicate and commit all uncommitted logs. If there is any uncommitted config log, that should be committed as well.

But, whenever a server becomes a leader, it should generate a new config log with the term it has, and that config should be based on the latest config it has, and that latest config might be an uncommitted one. So above logic is to find the latest config.

**Comment by JackyWoo** [comment]
Got it, Thank you.
