### ISSUE TITLE
Limit client append entry size

### ISSUE THREAD

**Issue by JackyWoo** [eBay/NuRaft#297]
I wonder whether we should limit the client append entry size. If not there will be extremely large entries theoretically, which will lead a client log batch will be distributed to followers by more than one batch. Maybe this will lead to something bad.

I notice there is a config `max_append_size_` who will limit log size to distribute to follower once, but it does limit the client appending size. 

1. So maybe we can use it or
2. Add a new one  `max_client_append_size_` for example.

**Comment by greensky00** [comment]
That (having config for the max appending logs) should be done by the application (the user of NuRaft) before calling `append_entries()` API, not by NuRaft.
