### ISSUE TITLE
Client thread return error if gap between log store and state machine is too large in leader.

### ISSUE THREAD

**Issue by JackyWoo** [eBay/NuRaft#298]
When log replication is slow the gap will be large whih may lead to client timeout. As my understanding when timeout occur client does not know what is happening whether the request will be commited or lose.  So we'd better avoid timeout and return unambiguous response to client.

Maybe we can add a limit to gap between log store and state machine, when reaches return error code to client.

Correct me if my understanding is wrong.

If the idea is ok I'd like to work on it.

**Comment by greensky00** [comment]
Similar to https://github.com/eBay/NuRaft/issues/297, that should be done by the application (the user of NuRaft). The application is able to know the gap by APIs provided by NuRaft and can fail fast without calling the `append_entries()` API.

**Comment by JackyWoo** [comment]
Got it  thanks
