### ISSUE TITLE
Graceful Leader Removal from Cluster

### ISSUE THREAD

**Issue by marcusolini** [eBay/NuRaft#300]
Hi. I'm looking for guidance on how to gracefully remove an active leader node from a cluster. Since a leader cannot remove itself, is there an api/approach to have a leader relinquish it's leadership role so it can request to be removed from a new leader? The discussion use-case is that the nuraft cluster is elastic and nodes can be decommissioned externally without knowledge of leadership or knowledge of remove/shutdown procedures. Any insights or suggestions are appreciated.

**Comment by greensky00** [comment]
Hi @marcusolini 

There are two ways to do it:

* Let leader resign, or
https://github.com/eBay/NuRaft/blob/262e90b6d2b0a6311565cafe78b8d74c51878217/include/libnuraft/raft_server.hxx#L339-L340

* Let one of the followers take over the leadership
https://github.com/eBay/NuRaft/blob/262e90b6d2b0a6311565cafe78b8d74c51878217/include/libnuraft/raft_server.hxx#L349

Once the other follower becomes the next leader, you can safely decommission the old leader.

**Comment by marcusolini** [comment]
Thanks @greensky00 for the helpful quick response!

Is it possible to use the set_priority(...) method with priority set to 0 (before or after calling yield_leadership) to ensure the current leader (that is yielding its leadership) not to obtain the leadership role again? I guess the question is, is there a way to ensure that the current leader that is yielding leadership does not become the leader?

**Comment by greensky00** [comment]
Yes, setting the priority of the old leader to 0 works as you expected.

But please note that there is a case that the old leader is the only candidate who can be the next leader again. For example:
* There are 3 servers: S1 (current leader), S2, S3.
  * S1's log index: 10
  * S2: offline
  * S3's log index: 9

In such a case, S1 is the only member who can be the next leader. If you set the priority of S1 to 0, the entire cluster will be just stuck. So we have the below option and the default value is `true`.
https://github.com/eBay/NuRaft/blob/262e90b6d2b0a6311565cafe78b8d74c51878217/include/libnuraft/raft_params.hxx#L459-L467

However, the above case will be very rare as `yield_leadership` with `immediate_yield = false` will do catch-up first (sending log 10 to S3) and then resign.

**Comment by marcusolini** [comment]
Thank you @greensky00 for the comprehensive insight! Your time and help is appreciated. Cheers.
