### ISSUE TITLE
Does NuRaft recovery need state transfer?

### ISSUE THREAD

**Issue by Steamgjk** [eBay/NuRaft#345]
In the original Raft paper, when leader crashes and is relaunched, joins as a follower, it needs to recover its log first. Different from Viewstamped Replication, it does not have state transfer mechanism, and it directly recovers the state from its stable storage. 

Since the open-source NuRaft does not have a stable backend, when leader crashes and is relaunched, how will the leader recover its state?

**Comment by greensky00** [comment]
Below is what will happen after a server restart:

1. NuRaft calls `state_machine::last_commit_index()`. Your state machine should return the last durable log index, let's say it is `X`.
2. The server will receive the latest committed log index from the new leader, let's say it is `Y`, where `Y >= X`.
3. NuRaft will read log by calling the API of `log_store` and execute `state_machine::commit()` for all logs  from `X+1` to `Y`.

So it depends on how durable your log store and state machine implementations are.

**Comment by Steamgjk** [comment]
> Below is what will happen after a server restart:
> 
>     1. NuRaft calls `state_machine::last_commit_index()`. Your state machine should return the log index of the last committed state, let's say it is `X`.
> 
>     2. The server will receive the latest committed log index from the new leader, let's say it is `Y`, where `Y >= X`.
> 
>     3. NuRaft will read log by calling the API of `log_store` and execute `state_machine::commit()` for all logs  from `X+1` to `Y`.
> 
> 
> So it depends on how durable your log store and state machine implementations are.

Hi @greensky00 
Let's say last_commit_index-0 (i.e. there is no snapshot persisted and the state is completely volatile and lost after crash). 

And log_store is also in-memory store and completely lost. In that case, will NuRaft still recover or not?

I am curious about this question because my colleague previously did a recovery experiment with NuRaft. I am pretty sure that he is using the in-memory store, so the log will be lost after leader crash, so in that way, if there is no state transfer from other replicas, the recovery process shoud be incorrect. But anyway, he generated the experiment result. Then my question is: Regarding the codebase, if the leader crashes and the log_store becomes empty, is the recovery procedure still be able to be executed and completed?

**Comment by greensky00** [comment]
Even though the log store and state machine are completely volatile, the above procedure works in the same way:
* The new leader checks the last log index of the restarted server (which is `0`) from the response of the heartbeat.
* The new leader sends all logs starting from `1`.
  * If the log of the new leader is already compacted, it will send a snapshot.
* The restarted server commits the received logs sequentially.

**Comment by Steamgjk** [comment]
Got it. Thanks @greensky00
