### ISSUE TITLE
client-service model quesiton

### ISSUE THREAD

**Issue by BozeBro** [eBay/NuRaft#369]
If we wanted to separate the client from the server, like the client sends requests over a network, is there a way to do that in this library or does this require our own separate implementation?

**Comment by greensky00** [comment]
This library has such a protocol to handle client requests over the network:
https://github.com/eBay/NuRaft/blob/50031e1b230569ccaa46008fc09d401e3e5c5985/src/raft_server.cxx#L636-L639
but we don't recommend it as it is inconvenient and lack functionalities such as error handling and throttling.

In eBay, we use our own server-client implementation using gRPC of REST API, and the server operates NuRaft with local `append_entries()` API call.

**Comment by BozeBro** [comment]
Does a client implementation exist in the library or is this also left up to the developer?

**Comment by greensky00** [comment]
It is not in the library, you should write your own one with Asio.
