### ISSUE TITLE
brew install nuraft

### ISSUE THREAD

**Issue by ankane** [eBay/NuRaft#378]
Hi, just wanted to share that NuRaft is now available on Homebrew, so Homebrew users can install it (and its dependencies) with:

```sh
brew install nuraft
```

Homebrew precompiles libraries for Mac x86-64, Mac arm64, and Linux x86-64, so installation is pretty much instant 🎉 

Ref: https://github.com/Homebrew/homebrew-core/pull/111691

**Comment by greensky00** [comment]
Wow, really excited to hear that! :raised_hands: much appreciate it @ankane 

Actually, we are working on v2.0.0 including the recent features, and will make a new tag soon. Can I ask you a favor to register the new version once we've done it? Thanks!

**Comment by ankane** [comment]
Nice. Homebrew is really good about keeping things up-to-date as new releases happen (just tag as normal), but feel free to ping me on this issue and I'll take a look.
