### ISSUE TITLE
Whether we should add consistency test.

### ISSUE THREAD

**Issue by JackyWoo** [eBay/NuRaft#408]
Whether we should add consistency test such as `Jepsen`?

**Comment by greensky00** [comment]
NuRaft is not a standalone system but an embedded library. Its behavior varies according to the plugged state machine, log store, and so on. Given that, Jepsen sounds overkill in this library; such tests should be done in the upper layer (who owns the implemented state machine and log store).

**Comment by JackyWoo** [comment]
Thanks.
