### ISSUE TITLE
Clean up CMakeLists

### ISSUE THREAD

**Issue by JosiahWI** [eBay/NuRaft#450]
Hello, I'm a contributor to Apache Trafficserver and I'm part of an effort to move our build to CMake. One of our plugins depends on NuRaft, and I'm investigating how we should detect it in our build. It doesn't look like you export your targets, so will we have to write our own Find script? I am willing to PR the necessary changes to your CMakeLists.txt to export targets, to make this cleaner in the future. At the same time, I'm willing to do some other clean up; in particular, I am curious why you wrote your own logic to detect OpenSSL when `find_package(OpenSSL)` exists.

**Comment by JosiahWI** [comment]
Looks like #358 already addresses that later concern. I would be happy to pick up that PR if the original author is no longer working on it.

**Comment by greensky00** [comment]
Hi @JosiahWI 
please go ahead and make a PR about exporting target. Let me review it.

Regarding Open SSL -- we don't want to break existing building script with pre-configured library path. If you can take over the PR and address the things I mentioned in the comment, that will be great. Thanks.
