### ISSUE TITLE
This is a question, not an issue. About `state_machine::pre_commit`

### ISSUE THREAD

**Issue by zidian666** [eBay/NuRaft#474]
https://github.com/eBay/NuRaft/blob/e66b4b65c90ff3a0be852d484bf15583672ea7fd/include/libnuraft/state_machine.hxx#L99

I'm confused about the return value of this function.

If I want to return a non-null pointer, how can I know NuRaft how to deserialize it ?

Actually, I'm going to let `state_machine::pre_commit` return a failure to make pre-commit fail.
Or is there another way to make pre-commit fail ?

Thanks.

**Comment by greensky00** [comment]
@zidian666 
`pre_commit` is executed right after appending the log to log store, hence it is not possible to make it fail; once a log is appended, it should be replicated. `commit` may not be invoked according to the consensus result though.

The return value of `pre_commit` is not used in normal path. There is a special option "[asynchronous replication]"(https://github.com/eBay/NuRaft/blob/master/docs/async_replication.md) which returns the result of `pre_commit` without waiting for the consensus. Other than that, its return value is just ignored.

**Comment by zidian666** [comment]
So `pre-commit` will only fail due to poor network conditions ?
