### ISSUE TITLE
Does nuraft support linearizable read if generating no raft log entry of read requests?

### ISSUE THREAD

**Issue by Brokenice0415** [eBay/NuRaft#475]
Serving every read request as a write one is unacceptable for the cost.

Does nuraft offer any way to support linearizable read, like ReadIndex or LeaderLease?

I have seen a similar issue #288, but it seems that the linearizable read in this issue still needs to generate raft log entries of read requests.

**Comment by greensky00** [comment]
You can refer to the original [Raft paper](https://raft.github.io/raft.pdf), section 8 Client interaction. To achieve linearizable read, you must always read the data from the leader.

NuRaft provides an option to avoid overlapping time window between old leader and new leader, by having [leadership expiration](https://github.com/eBay/NuRaft/blob/master/docs/leadership_expiration.md). That guarantees, if the current leader is alive and valid, its data is always fresh and there is no newer leader.

**Comment by Brokenice0415** [comment]
Hi @greensky00 , thanks for your explanation! I have read the section in detail and understood how nuraft ensures the linearizable read better!
