### ISSUE TITLE
rpc_listener

### ISSUE THREAD

**Issue by as51340** [eBay/NuRaft#520]
Could you briefly explain what are rpc_listeners used for? Cannot find anything in docs about it...

Thanks,
Andi

**Comment by greensky00** [comment]
@as51340 Sorry I missed this question. 

The rpc_listeners, which are realized by asio_rpc_listener, act as servers responsible for processing incoming RPC requests. Typically, the leader acts as a client that sends out append_entries requests, while the followers serve as listeners, essentially operating as servers.

**Comment by as51340** [comment]
thanks @greensky00 !
