### ISSUE TITLE
Leader expiration

### ISSUE THREAD

**Issue by andy-yx-chen** [eBay/NuRaft#69]
There is an optimization in cornerstone that introduces leader expiration to prevent a node thinks itself as a leader forever if it's isolated, see [this](https://github.com/datatechnology/cornerstone/commit/a25a730ed75c551623e17f595198f75e7927ac7c), do you want to port it?

**Comment by greensky00** [comment]
Hi @andy-yx-chen , we also have [leadership expiration](https://github.com/eBay/NuRaft/blob/master/docs/leadership_expiration.md).

Please note that (I remember we also had discussion through e-mail a few months ago), at least in eBay's use cases, just denying requests is not enough. Other service components behave differently according to the role of node (e.g. query type, admin operations), thus leader should step down itself immediately if it detects this kind of isolation.
