### ISSUE TITLE
Please help: cannot add server, error code -7

### ISSUE THREAD

**Issue by xuluna** [eBay/NuRaft#83]
Same code deployed in 3 machines: {1,2,3}. Tries to add_srv in 1, and can add only one more machine (either 2 or 3), when adding one more, it gives error -7. Code is the same, why for example adding 2 is successful but unsuccessful when adding one more (3)?

**Comment by greensky00** [comment]
Hi @xuluna, you can add only one server at a time. Return code `-7` means previous adding server operation is still in progress. Are you seeing this result in basic examples? 

Also please make sure that when you add a server, that server should be online.

**Comment by xuluna** [comment]
@greensky00 Thank you so much for quick response! Yes I can guarantee the servers are all online. Then, in this case, how can I know when the previous request is done and I can add another server?

**Comment by greensky00** [comment]
@xuluna Since adding server is an asynchronous operation (as it will do data sync or snapshot transmission, may take long time), you need to do polling using below API:
https://github.com/eBay/NuRaft/blob/9eddae8fc775ee3f204dbcf25a9f5ee7bad11c4e/include/libnuraft/raft_server.hxx#L355
If adding server is not done yet, it will return `nullptr`.

A naive example of waiting for adding server is done, in Benchmark tool:
https://github.com/eBay/NuRaft/blob/9eddae8fc775ee3f204dbcf25a9f5ee7bad11c4e/tests/bench/raft_bench.cxx#L249

**Comment by xuluna** [comment]
@greensky00 Thanks! Sorry but I encountered another error:asio_service.cxx:operator():305: session 1 failed to read rpc header from socket 9.1.75.37:59884 due to error 2. This message is from a follower, there's no error message from the leader. I don't know why the port number is 59884. The leader's info is like this:
peer 1, DC ID 0, 9.1.75.37:9999, voting member, 1                                                                                                                                        
peer 2, DC ID 0, 9.1.75.3:9999, voting member, 1                                                                                                
my id: 1, leader: 1, term: 1
Both ports should be 9999.

**Comment by greensky00** [comment]
Hi @xuluna, 
If you meant below message in follower,
```
session 1 failed to read rpc header from socket 127.0.0.1:48174 due to error 2  [asio_service.cxx:305, operator()()]
```
please note that is normal and you can treat it as one-time false alarm. Whenever the sync-up with newly joining server is done, the leader closes previous channel (used for data sync) and then opens a new channel (for normal Raft protocol). 

From follower's point of view, that error message shows up when the current connection is closed by leader.

If that message disrupts you, maybe we can provide a patch for workaround. Thanks.

**Comment by xuluna** [comment]
@greensky00 Thank you for your patient explanation! I'm fine with that message.
